version: '1.0'

services:
 web:
  build: 
    context: .
    dockerfile: ./docker/Dockerfile
  ports: 
    - "5000:5000"
  volumes:
    - .:/app
  environment:
    - FLASK_APP=main.py
    - FLASK_RUN_HOST=0.0.0.0
