name: build-docker-images

on:
  push:
    branches:
      - main
      - development

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        platform: [amd64] # multi-architecture [amd64, arm64]

    outputs:
      platforms: ${{ matrix.platform }}
      git_sha: ${{ env.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Git commit SHA
        id: git_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image (Python)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          output: type=docker
          push: false
          tags: capstone-vulnerable-python:${{ env.sha }}-${{ matrix.platform }}

  
  publish: # Reference publish.yaml workflow
    needs: build # This job depends on the successful completion of "build"
    uses: ./.github/workflows/publish.yaml
    secrets: inherit # pass all secrets
    with:
      platforms: ${{ needs.build.outputs.platforms }}
      git_sha: ${{ needs.build.outputs.git_sha }}